theme: jekyll-theme-hacker
title: CS1999 tech notes
description: "Tech notes for the CS1999 Buggy Race Editor"
show_downloads: false

#---------------------------------------------------------------------
# custom URLs:
# these are used within the pages: check they are right!
#---------------------------------------------------------------------
editor_url: https://github.com/buggyrace/buggy-race-editor
moodle_url: https://moodle.example.com/course/view.php?id=8381
server_url: https://www.buggyrace.net

plugins:
  - jekyll-redirect-from
  - jekyll-optional-front-matter

optional_front_matter:
  remove_originals: true
