heroku_deploy:
  stage: deploy
  script:
    - pwd
    - export PATH="/opt/gitlab-runner/.local/share/gem/ruby/3.0.0/bin:$PATH"
    - echo HELLO
    - gem install --user-install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_PRODUCTION_KEY


