version: '3.6'

x-build-args: &build_args
  INSTALL_PYTHON_VERSION: 3.9
  INSTALL_NODE_VERSION: 14

x-default-volumes: &default_volumes
  volumes:
    - app_data:/app
    - published:/app/published
    - node-modules:/app/node_modules

services:
  buggy-race-db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/


  buggy-race-server:
    build:
      context: .
      target: production
      args:
        <<: *build_args
    image: 'buggy_race_server-production'
    ports:
      - '443:5000'
    env_file:
      - .env
    <<: *default_volumes
    depends_on:
      - buggy-race-db
    links:
      - buggy-race-db

volumes:
  app_data:
  published:
  node-modules:
  db_data:
    driver: local
