version: '3.6'

x-build-args: &build_args
  INSTALL_PYTHON_VERSION: 3.8
  INSTALL_NODE_VERSION: 14

x-default-volumes: &default_volumes
  volumes:
    - ./:/app
    - node-modules:/app/node_modules
    - ./dev.db:/tmp/dev.db

services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=superuser
      # TODO: Auto-generate this
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=buggy_race
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/


  flask-dev:
    build:
      context: .
      target: development
      args:
        <<: *build_args
    image: "buggy_race_server-development"
    ports:
      - "443:5000"
    env_file:
      - .env
    environment:
      FLASK_ENV: development
      LOG_LEVEL: debug
      GUNICORN_WORKERS: 1
    <<: *default_volumes
    depends_on:
      - db
    links:
      - db


  flask-prod:
    build:
      context: .
      target: production
      args:
        <<: *build_args
    image: "buggy_race_server-production"
    ports:
      - "443:5000"
    env_file:
      - .env
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
      LOG_LEVEL: info
      GUNICORN_WORKERS: 1
    <<: *default_volumes
    depends_on:
      - db
    links:
      - db

volumes:
  node-modules:
  static-build:
  dev-db:
  db_data:
    driver: local
