"""record user's first login

Revision ID: 00152d1270ad
Revises: 8541b7aad85a
Create Date: 2024-06-18 12:08:47.794473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00152d1270ad'
down_revision = '8541b7aad85a'
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_logged_in_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('first_logged_in_at')

    # ### end Alembic commands ###
