"""add sort order to tasks

Revision ID: 1c0173d29fcf
Revises: 1c9f1f6af189
Create Date: 2023-01-31 00:19:33.193994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c0173d29fcf'
down_revision = '1c9f1f6af189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('sort_position', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'sort_position')
    # ### end Alembic commands ###
