"""empty message

Revision ID: 1d85c24f0529
Revises: 456f160eff05
Create Date: 2022-04-29 19:22:16.093225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d85c24f0529'
down_revision = '456f160eff05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rhul_username', sa.String(length=80), nullable=True))
    op.create_unique_constraint(None, 'users', ['rhul_username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'rhul_username')
    # ### end Alembic commands ###
