"""add racetracks

Revision ID: 1e467539c0d2
Revises: 6d6833ac6989
Create Date: 2023-06-10 01:29:44.873463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e467539c0d2'
down_revision = '6d6833ac6989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('racetracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('track_image_url', sa.String(length=255), nullable=True),
    sa.Column('track_svg_url', sa.String(length=255), nullable=True),
    sa.Column('lap_length', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('racetracks')
    # ### end Alembic commands ###
