"""empty message

Revision ID: 22d90ea65a8c
Revises: dd10ff34c48b
Create Date: 2021-04-24 10:15:32.183155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22d90ea65a8c'
down_revision = 'dd10ff34c48b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_access_token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'github_access_token')
    # ### end Alembic commands ###
