"""add race league

Revision ID: 456f160eff05
Revises: 78b5f16bd9a2
Create Date: 2021-06-06 16:50:59.301612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '456f160eff05'
down_revision = '78b5f16bd9a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('races', sa.Column('league', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('races', 'league')
    # ### end Alembic commands ###
