"""racetrack length data

Revision ID: 4e6d71ff8faa
Revises: 1c327d0803e4
Create Date: 2025-07-30 16:01:27.225142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e6d71ff8faa'
down_revision = '1c327d0803e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.add_column(sa.Column('svg_path_length', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('start_offset', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('finish_offset', sa.Integer(), nullable=True))

    with op.batch_alter_table('racetracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_image', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('image_media_type', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('track_svg', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('svg_path_length', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('start_offset', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('finish_offset', sa.Integer(), nullable=True))

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('racetracks', schema=None) as batch_op:
        batch_op.drop_column('finish_offset')
        batch_op.drop_column('start_offset')
        batch_op.drop_column('svg_path_length')
        batch_op.drop_column('track_svg')
        batch_op.drop_column('image_media_type')
        batch_op.drop_column('track_image')

    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.drop_column('finish_offset')
        batch_op.drop_column('start_offset')
        batch_op.drop_column('svg_path_length')

    # ### end Alembic commands ###
