"""add admin_tint to user

Revision ID: 520e84bc1e0e
Revises: da24495f7e73
Create Date: 2026-06-02 00:46:57.121375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '520e84bc1e0e'
down_revision = 'da24495f7e73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_tint', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('admin_tint')

    # ### end Alembic commands ###
