"""rename org- to ext- (external) username

Revision ID: 53f1efba5b0f
Revises: bfe9a35ec7a3
Create Date: 2023-03-07 16:33:28.176360

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '53f1efba5b0f'
down_revision = 'bfe9a35ec7a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ext_username', sa.String(length=80), nullable=True))
    op.drop_index('org_username', table_name='users')
    op.create_unique_constraint(None, 'users', ['ext_username'])
    op.drop_column('users', 'org_username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('org_username', mysql.VARCHAR(length=80), nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('org_username', 'users', ['org_username'], unique=False)
    op.drop_column('users', 'ext_username')
    # ### end Alembic commands ###
