"""empty message

Revision ID: 6136d04d9e5c
Revises: a2b55be4d74b
Create Date: 2021-05-23 15:27:10.629956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6136d04d9e5c'
down_revision = 'a2b55be4d74b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uploaded_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'uploaded_at')
    # ### end Alembic commands ###
