"""buggy csv url not unique

Revision ID: 6d6833ac6989
Revises: 7663bd1779cb
Create Date: 2023-06-09 18:14:18.029261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d6833ac6989'
down_revision = '7663bd1779cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('races', 'buggies_csv_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('races', sa.Column('buggies_csv_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###
