"""buggy csv url not unique

Revision ID: 6d6833ac6989
Revises: 7663bd1779cb
Create Date: 2023-06-09 18:14:18.029261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d6833ac6989'
down_revision = '7663bd1779cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('buggies_csv_url', table_name='races')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('buggies_csv_url', 'races', ['buggies_csv_url'], unique=False)
    # ### end Alembic commands ###
