"""empty message

Revision ID: 78b5f16bd9a2
Revises: 7367a05d682a
Create Date: 2021-06-06 10:52:13.420512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78b5f16bd9a2'
down_revision = '7367a05d682a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notes')
    # ### end Alembic commands ###
