"""empty message

Revision ID: 7c4ab168141f
Revises: ab9b30aa47a3
Create Date: 2023-07-08 17:16:07.785084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c4ab168141f'
down_revision = 'ab9b30aa47a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_dnf_position', sa.Boolean(), nullable=True))

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.drop_column('is_dnf_position')

    # ### end Alembic commands ###
