"""add api secret use counter

Revision ID: 7c8fba60b31f
Revises: c94030a9d285
Create Date: 2023-03-30 09:00:01.715657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c8fba60b31f'
down_revision = 'c94030a9d285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_secret_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'api_secret_count')
    # ### end Alembic commands ###
