"""empty message

Revision ID: 7cd765e02109
Revises: 6136d04d9e5c
Create Date: 2021-05-30 17:17:17.501392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd765e02109'
down_revision = '6136d04d9e5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_secret', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('api_secret_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'api_secret_at')
    op.drop_column('users', 'api_secret')
    # ### end Alembic commands ###
