"""add lap_length to races

Revision ID: 874eb844e1ac
Revises: 1e467539c0d2
Create Date: 2023-06-11 17:26:30.421686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '874eb844e1ac'
down_revision = '1e467539c0d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('races', sa.Column('lap_length', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('races', 'lap_length')
    # ### end Alembic commands ###
