"""empty message

Revision ID: a2b55be4d74b
Revises: ce5574dd2a45
Create Date: 2021-05-23 13:12:07.912676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b55be4d74b'
down_revision = 'ce5574dd2a45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('logged_in_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'logged_in_at')
    # ### end Alembic commands ###
