"""add external id to user

Revision ID: a38ed3aabb7a
Revises: 500f64923fd2
Create Date: 2023-04-13 10:45:46.333928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a38ed3aabb7a'
down_revision = '500f64923fd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ext_id', sa.String(length=80), nullable=True))
    op.create_unique_constraint(None, 'users', ['ext_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'ext_id')
    # ### end Alembic commands ###
