"""empty message

Revision ID: a58d1c882f44
Revises: 
Create Date: 2021-02-13 02:23:56.210304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a58d1c882f44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('password', sa.LargeBinary(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('latest_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('buggies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('buggy_id', sa.Integer(), nullable=True),
    sa.Column('qty_wheels', sa.Integer(), nullable=True),
    sa.Column('flag_color', sa.String(length=32), nullable=True),
    sa.Column('flag_color_secondary', sa.String(length=32), nullable=True),
    sa.Column('flag_pattern', sa.String(length=8), nullable=True),
    sa.Column('power_type', sa.String(length=16), nullable=True),
    sa.Column('power_units', sa.Integer(), nullable=True),
    sa.Column('aux_power_type', sa.String(length=16), nullable=True),
    sa.Column('aux_power_units', sa.Integer(), nullable=True),
    sa.Column('tyres', sa.String(length=16), nullable=True),
    sa.Column('qty_tyres', sa.Integer(), nullable=True),
    sa.Column('armour', sa.String(length=16), nullable=True),
    sa.Column('attack', sa.String(length=16), nullable=True),
    sa.Column('qty_attacks', sa.Integer(), nullable=True),
    sa.Column('hamster_booster', sa.Integer(), nullable=True),
    sa.Column('fireproof', sa.Boolean(), nullable=True),
    sa.Column('insulated', sa.Boolean(), nullable=True),
    sa.Column('antibiotic', sa.Boolean(), nullable=True),
    sa.Column('banging', sa.Boolean(), nullable=True),
    sa.Column('algo', sa.String(length=16), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Integer(), nullable=True),
    sa.Column('mass', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    op.drop_table('buggies')
    op.drop_table('users')
    # ### end Alembic commands ###
