"""add user access level

Revision ID: b140f6e2d761
Revises: 318931324601
Create Date: 2023-03-18 08:25:53.905398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b140f6e2d761'
down_revision = '318931324601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_level', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'access_level')
    # ### end Alembic commands ###
