"""is user API secret one-time pw

Revision ID: c94030a9d285
Revises: 57a458972f11
Create Date: 2023-03-29 22:49:58.895766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c94030a9d285'
down_revision = '57a458972f11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_api_secret_otp', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_api_secret_otp')
    # ### end Alembic commands ###
