"""empty message

Revision ID: ce5574dd2a45
Revises: 22d90ea65a8c
Create Date: 2021-05-08 18:21:42.110065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce5574dd2a45'
down_revision = '22d90ea65a8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_student', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_student')
    # ### end Alembic commands ###
