"""users' custom project notices, deadlines and links

Revision ID: da24495f7e73
Revises: 4e6d71ff8faa
Create Date: 2026-03-24 21:35:04.719826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da24495f7e73'
down_revision = '4e6d71ff8faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_notice', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('submission_deadline', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('submission_link', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('submission_link')
        batch_op.drop_column('submission_deadline')
        batch_op.drop_column('project_notice')

    # ### end Alembic commands ###
