"""unqiue race urls

Revision ID: da84ffb9b64e
Revises: b140f6e2d761
Create Date: 2023-03-28 00:15:26.204350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da84ffb9b64e'
down_revision = 'b140f6e2d761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'races', ['buggies_csv_url'])
    op.create_unique_constraint(None, 'races', ['race_log_url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'races', type_='unique')
    op.drop_constraint(None, 'races', type_='unique')
    # ### end Alembic commands ###
