"""empty message

Revision ID: dd10ff34c48b
Revises: a58d1c882f44
Create Date: 2021-04-23 13:50:13.467151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd10ff34c48b'
down_revision = 'a58d1c882f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_username', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'github_username')
    # ### end Alembic commands ###
