"""empty message

Revision ID: e31e4c7dfd39
Revises: 8634dc66be87
Create Date: 2025-07-28 18:45:44.239227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e31e4c7dfd39'
down_revision = '8634dc66be87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_offset', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('finish_offset', sa.Integer(), nullable=True))

    with op.batch_alter_table('racetracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_offset', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('finish_offset', sa.Integer(), nullable=True))

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('racetracks', schema=None) as batch_op:
        batch_op.drop_column('finish_offset')
        batch_op.drop_column('start_offset')

    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.drop_column('finish_offset')
        batch_op.drop_column('start_offset')

    # ### end Alembic commands ###
