"""add word count to task texts

Revision ID: f9296dab7503
Revises: 520e84bc1e0e
Create Date: 2026-06-09 12:02:30.850559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9296dab7503'
down_revision = '520e84bc1e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasktexts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('word_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasktexts', schema=None) as batch_op:
        batch_op.drop_column('word_count')

    # ### end Alembic commands ###
